export const categories = [
  {
    id: "electronics",
    name: "Electrónicos",
    slug: "electronics",
    description: "Dispositivos electrónicos y gadgets",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "home",
    name: "Hogar",
    slug: "home",
    description: "Productos para el hogar y decoración",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "fashion",
    name: "Moda",
    slug: "fashion",
    description: "Ropa, calzado y accesorios",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "sports",
    name: "Deportes",
    slug: "sports",
    description: "Equipamiento deportivo y accesorios",
    image: "/placeholder.svg?height=400&width=600",
  },
]

export const products = [
  {
    id: "smartphone-1",
    name: "Smartphone Galaxy S23",
    description: "Smartphone de última generación con cámara de alta resolución y batería de larga duración.",
    price: 699990,
    image: "/placeholder.svg?height=400&width=400",
    categoryId: "electronics",
    categoryName: "Electrónicos",
    categorySlug: "electronics",
    knasta: {
      price: 599990,
      url: "https://knasta.cl/producto/smartphone-galaxy-s23",
    },
    specs: [
      { name: "Pantalla", value: "6.1 pulgadas AMOLED" },
      { name: "Procesador", value: "Snapdragon 8 Gen 2" },
      { name: "RAM", value: "8GB" },
      { name: "Almacenamiento", value: "256GB" },
      { name: "Cámara", value: "50MP + 12MP + 10MP" },
      { name: "Batería", value: "3900mAh" },
    ],
  },
  {
    id: "laptop-1",
    name: "Laptop UltraBook Pro",
    description: "Laptop ultradelgada con procesador de alto rendimiento y pantalla de alta resolución.",
    price: 1299990,
    image: "/placeholder.svg?height=400&width=400",
    categoryId: "electronics",
    categoryName: "Electrónicos",
    categorySlug: "electronics",
    knasta: {
      price: 1199990,
      url: "https://knasta.cl/producto/laptop-ultrabook-pro",
    },
    specs: [
      { name: "Pantalla", value: "15.6 pulgadas 4K" },
      { name: "Procesador", value: "Intel Core i7-12700H" },
      { name: "RAM", value: "16GB" },
      { name: "Almacenamiento", value: "1TB SSD" },
      { name: "Gráficos", value: "NVIDIA RTX 3060" },
      { name: "Batería", value: "10 horas" },
    ],
  },
  {
    id: "headphones-1",
    name: "Audífonos Noise Cancelling",
    description: "Audífonos inalámbricos con cancelación de ruido activa y sonido de alta fidelidad.",
    price: 249990,
    image: "/placeholder.svg?height=400&width=400",
    categoryId: "electronics",
    categoryName: "Electrónicos",
    categorySlug: "electronics",
    knasta: {
      price: 199990,
      url: "https://knasta.cl/producto/audifonos-noise-cancelling",
    },
    specs: [
      { name: "Tipo", value: "Over-ear" },
      { name: "Conectividad", value: "Bluetooth 5.2" },
      { name: "Cancelación de ruido", value: "Activa" },
      { name: "Batería", value: "30 horas" },
      { name: "Carga rápida", value: "Sí" },
      { name: "Micrófono", value: "Integrado" },
    ],
  },
  {
    id: "sofa-1",
    name: "Sofá Modular Comfort",
    description: "Sofá modular de 3 cuerpos con tela de alta calidad y diseño contemporáneo.",
    price: 899990,
    image: "/placeholder.svg?height=400&width=400",
    categoryId: "home",
    categoryName: "Hogar",
    categorySlug: "home",
    knasta: {
      price: 949990,
      url: "https://knasta.cl/producto/sofa-modular-comfort",
    },
    specs: [
      { name: "Material", value: "Tela premium" },
      { name: "Estructura", value: "Madera de pino" },
      { name: "Dimensiones", value: "280x180x85 cm" },
      { name: "Asientos", value: "3" },
      { name: "Color", value: "Gris oscuro" },
      { name: "Garantía", value: "2 años" },
    ],
  },
  {
    id: "table-1",
    name: "Mesa de Centro Nórdica",
    description: "Mesa de centro con diseño nórdico, fabricada en madera de roble y patas de metal.",
    price: 199990,
    image: "/placeholder.svg?height=400&width=400",
    categoryId: "home",
    categoryName: "Hogar",
    categorySlug: "home",
    knasta: {
      price: 159990,
      url: "https://knasta.cl/producto/mesa-centro-nordica",
    },
    specs: [
      { name: "Material", value: "Madera de roble" },
      { name: "Patas", value: "Metal negro" },
      { name: "Dimensiones", value: "120x60x45 cm" },
      { name: "Estilo", value: "Nórdico" },
      { name: "Peso", value: "15 kg" },
      { name: "Montaje", value: "Requerido" },
    ],
  },
  {
    id: "lamp-1",
    name: "Lámpara de Pie Moderna",
    description: "Lámpara de pie con diseño moderno, perfecta para iluminar cualquier espacio de tu hogar.",
    price: 89990,
    image: "/placeholder.svg?height=400&width=400",
    categoryId: "home",
    categoryName: "Hogar",
    categorySlug: "home",
    knasta: {
      price: 79990,
      url: "https://knasta.cl/producto/lampara-pie-moderna",
    },
    specs: [
      { name: "Material", value: "Metal y tela" },
      { name: "Altura", value: "160 cm" },
      { name: "Tipo de bombilla", value: "E27" },
      { name: "Potencia máxima", value: "60W" },
      { name: "Color", value: "Negro" },
      { name: "Interruptor", value: "De pie" },
    ],
  },
  {
    id: "jacket-1",
    name: "Chaqueta Impermeable Mountain",
    description:
      "Chaqueta impermeable para actividades al aire libre con tecnología de protección contra el viento y la lluvia.",
    price: 149990,
    image: "/placeholder.svg?height=400&width=400",
    categoryId: "fashion",
    categoryName: "Moda",
    categorySlug: "fashion",
    knasta: {
      price: 129990,
      url: "https://knasta.cl/producto/chaqueta-impermeable-mountain",
    },
    specs: [
      { name: "Material", value: "Poliéster reciclado" },
      { name: "Impermeabilidad", value: "10.000mm" },
      { name: "Transpirabilidad", value: "8.000g/m²" },
      { name: "Capucha", value: "Ajustable" },
      { name: "Bolsillos", value: "4 con cierre" },
      { name: "Tallas", value: "S, M, L, XL" },
    ],
  },
  {
    id: "sneakers-1",
    name: "Zapatillas Running Pro",
    description: "Zapatillas de running con amortiguación avanzada y diseño ligero para máximo rendimiento.",
    price: 119990,
    image: "/placeholder.svg?height=400&width=400",
    categoryId: "fashion",
    categoryName: "Moda",
    categorySlug: "fashion",
    knasta: {
      price: 99990,
      url: "https://knasta.cl/producto/zapatillas-running-pro",
    },
    specs: [
      { name: "Material", value: "Malla transpirable" },
      { name: "Suela", value: "Goma de alta resistencia" },
      { name: "Amortiguación", value: "Tecnología Boost" },
      { name: "Peso", value: "280g" },
      { name: "Drop", value: "10mm" },
      { name: "Tallas", value: "38-45" },
    ],
  },
  {
    id: "backpack-1",
    name: "Mochila Urbana Tech",
    description: "Mochila urbana con compartimentos para laptop y dispositivos electrónicos, resistente al agua.",
    price: 79990,
    image: "/placeholder.svg?height=400&width=400",
    categoryId: "fashion",
    categoryName: "Moda",
    categorySlug: "fashion",
    knasta: null,
    specs: [
      { name: "Material", value: "Poliéster balístico" },
      { name: "Capacidad", value: "25L" },
      { name: "Compartimentos", value: "5" },
      { name: "Laptop", value: "Hasta 15.6 pulgadas" },
      { name: "Resistencia al agua", value: "Sí" },
      { name: "Color", value: "Negro" },
    ],
  },
]
